### ISSUE TITLE
Compatibility with gitmodules

### ISSUE THREAD

**Issue by Shreyanand** [thoth-station/jupyternb-build-pipeline#3]
As a user of jupyternb build pipeline, I would like to create images from repositories that have [gitmodules](https://git-scm.com/docs/gitmodules/2.10.5) 

An example of such a project is [categorical-encoding-internal](https://github.com/aicoe-aiops/categorical-encoding-internal)

**Comment by Shreyanand** [comment]
@chauhankaranraj @Sankbad Is there a already a way around this?

**Comment by chauhankaranraj** [comment]
> @chauhankaranraj @SankBad Is there a already a way around this?

I'm not sure tbh :confused:

**Comment by SankBad** [comment]
Hi @chauhankaranraj , 

I saw [Pipfile]( https://github.com/aicoe-aiops/ocp4-anomaly-detection/blob/master/Pipfile) for ocp4-anomaly-detection.
There are some entries like `kraken-core = {git = "https://gitlab.cee.redhat.com/ccx/kraken-core.git"}`
How exactly it works?

In my case, I am using the repo https://github.com/mattilyra/LSH
The author of the repo did not created a package but setup.py file is available. 
Can I enter to the entry like `lsh = {git = "git@github.com:mattilyra/LSH.git"}`

**Comment by fridex** [comment]
This feature is requesting to discard proper release management of packages (see for example golang world and a can of worms possibly opened with this approach). Also, this can be tricky to support on Thoth side.

Thoth is creating tooling to automate release+update process of packages - we can assist you if you want to package a Python code, and thoth bots can help you with release/update management of packages.

**Comment by chauhankaranraj** [comment]
> I saw [Pipfile](https://github.com/aicoe-aiops/ocp4-anomaly-detection/blob/master/Pipfile) for ocp4-anomaly-detection.
> There are some entries like `kraken-core = {git = "https://gitlab.cee.redhat.com/ccx/kraken-core.git"}`
> How exactly it works?

These entries are not git submodules, but rather "[VCS dependencies](https://pipenv-fork.readthedocs.io/en/latest/basics.html#a-note-about-vcs-dependencies)". These are not available on pypi, therefore we added them to the Pipfile like this.

> In my case, I am using the repo https://github.com/mattilyra/LSH
> The author of the repo did not created a package but setup.py file is available.
> Can I enter to the entry like `lsh = {git = "git@github.com:mattilyra/LSH.git"}`

It seems that in your repo, this package is just being used as-is, without any edits. If that's the case, then yes, I think you can add it as a dependency to your Pipfile as `lsh = {git = "https://github.com/mattilyra/LSH.git"}`, instead of trying to have it as a submodule.

**Comment by SankBad** [comment]
@chauhankaranraj , that was exactly my doubt. Thanks for clarifying :+1: 
I will test this locally to see if it works.

**Comment by harshad16** [comment]
The git submodules are handled by the server-side(like Github, GitLab). when we clone or download a repository, the git submodule's configuration only get downloaded as `.gitmodules`, according to my knowledge.
If this feature is to be implemented, it means, during the build process, the git submodule has to be copied along with the project.

Now looking at the example, categorical-encoding-internal
it feels like the sub modules,[string_categorical_encoders](https://github.com/Shreyanand/string_categorical_encoders/tree/d1bf15cf2992f7683952bb8bf7ed236ecab73772) should be converted into a python package which can be later installed in the application repository.

**Comment by goern** [comment]
Could you please ack/nack on this?

We do not allow git submodules in builds, as it introduces potential unrepeatable builds. We try to get away from VCS dependencies and release (maybe internal) python modules.

adding @durandom @vpavlin

**Comment by SankBad** [comment]
Hi all, 

Yesterday, I created a JH Image with a submodule in it. [Repo](https://github.com/aicoe-aiops/insights-configuration-files-analysis)
I found it didn't download .gitmodules but downloaded entire git submodule in the image. [Image](https://registry-console.upshift.redhat.com/registry#/images/aicoe-notebooks/insights-configuration-files-analysis)


Currently, I am facing an installation issue with s2i and hence not able to retest it.
Could someone retest this?

Note: If we are releasing a separate python module this comment is not relevant.

**Comment by harshad16** [comment]
> Yesterday, I created a JH Image with a submodule in it. [Repo](https://github.com/aicoe-aiops/insights-configuration-files-analysis)
> I found it didn't download .gitmodules but downloaded entire git submodule in the image. [Image](https://registry-console.upshift.redhat.com/registry#/images/aicoe-notebooks/insights-configuration-files-analysis)

That great, I saw the build process of that image, it seems the `.git` component is pulling the whole submodules based on `.gitmodules`. http://tekton-dashboard-tekton-pipelines.apps.thoth12.lab.upshift.rdu2.redhat.com/#/namespaces/jupyternb/pipelineruns/jupyternb-pipeline-build-q4f6l
Thanks for the update @SankBad 
 
@Shreyanand  can you also test it out and verify,  for [categorical-encoding-internal](https://github.com/aicoe-aiops/categorical-encoding-internal). if the image is as you require, then there is no feature to be added :rocket:.

**Comment by vpavlin** [comment]
I am voting *against* enabling the submodules. We will definitely want to follow the best practices around Python dependencies and submodules do not sound like something that would fit into that.

**Comment by durandom** [comment]
@fridex comment https://github.com/thoth-station/jupyternb-build-pipeline/issues/3#issuecomment-695038113 says it all. 
And you can specify dependencies via Pipfiles that point to git releases, so either that or a proper release.

-1 on submodules

**Comment by tumido** [comment]
Can we eagerly jump to conclusion then - let's define what should happen in such cases on the JH image source repository end:

1. If the dependency repo features a `setup.py`, or `pyproject.toml` (or whatever makes the repository buildable and installable as a git dependency via `pip`/`pipenv` nowadays) - use use the [pip's vcs support](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support) and lock to a commit/release
2. If it doesn't offer such way of installing, rather fork the dependency source repo, add `setup.py` and try to contribute it to upstream. In the meantime this fork can be used as a reference repo for approach 1.

If I'm reading the discussion properly, that should sum it up pretty well. Is that correct?

FTR, my view on this: https://github.com/aicoe-aiops/auto-faq/pull/9#issuecomment-697977130
> I personally take anything, that's not copypasting whole repositories. :slightly_smiling_face: And if it forces us to contribute to the upstream repositories adding `setup.py`'s everywhere, let's be it. At least we're making things installable for the whole world - and that counts. :slightly_smiling_face:

**Comment by fridex** [comment]
> Can we eagerly jump to conclusion then - let's define what should happen in such cases on the JH image source repository end:
> 
> 1. If the dependency repo features a `setup.py`, or `pyproject.toml` (or whatever makes the repository buildable and installable as a git dependency via `pip`/`pipenv` nowadays) - use use the [pip's vcs support](https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support) and lock to a commit/release
> 2. If it doesn't offer such way of installing, rather fork the dependency source repo, add `setup.py` and try to contribute it to upstream. In the meantime this fork can be used as a reference repo for approach 1.
> 
> If I'm reading the discussion properly, that should sum it up pretty well. Is that correct?

The very first step should be installing from a python package index. If a git repo is the only option, then use it for testing but do not push such code to prod.

**Comment by tumido** [comment]
@fridex 
> The very first step should be installing from a python package index. If a git repo is the only option, then use it for testing but do not push such code to prod.

Agreed with the first part, python package index should always be the first go-to place. I think the "why" the discussion about gitmodules even started was because the packages are not available there.

Usually in data science land, nobody bothers to publish their trained models (or similar) into PyPI. Most of the times people don't even bother writing down a proper `setup.py`. That's why we've started using git submodules at the first place - because there was no sane way to install those. Was it cutting corners? Probably yes.

Not sure what do you mean by "don't use it in production". In cases like these, when the PyPI package is not available (scenario 1) and (scenario 2, in addition to 1) the source repo doesn't even have `setup.py`, what you'd suggest us to do? If we shouldn't use git repo reference in prod. Fork it (maintain the fork) and push to some internal package index (maintain the package there)? I think that's too much out of scope for us unfortunately (especially the maintenance part of such forks, however there§s usually not much development going on on such packages anyways).

Example libraries we're talking about here:
- https://github.com/epfml/sent2vec (can be installed from git only)
- https://spacy.io/models (can be locked to a file and we currently use it that way, is that fine for production?)

There are few other dependencies we currently "install" via git submodules. However we currently have control over, or maintain a fork the said repos (I'm listing them here just for reference) - that means we can define `setup.py` for them. We probably can't or shouldn't publish forks onto PyPI though:
- https://github.com/Shreyanand/string_categorical_encoders
- https://github.com/SankBad/LSH

**Comment by fridex** [comment]
From a developer point of view - If the project does not have a proper maintenance and release cycle it says something about the project. Reaching out to maintainers is a good start - seeing how responsive and cooperative they are is also a sign of the project itself. Especially if you plan to use it long term. If you are really into the project, fork it and maintain it - the project is used somewhere (assuming you do this during work hours) so it will be maintained and will require some time.

Writing a setup.py is not that hard and reaching out to maintainers is always a good thing - they are usually happy that someone contributes and extends their work (my personal feeling when I see a new PR on my project). See for example https://github.com/seberg/pytest-valgrind/pull/1 as a community contract - I liked the project, I used it, I contributed back so the project can be used by others as well.

**Comment by tumido** [comment]
I totally get that point from engineering perspective like me and you reaching out to another engineer on the upstream end.

The perspective is a lot different for a data scientist. Python packaging is a completely new world. Projects and libraries "don't have a proper maintenance and release cycle" because they are part of some research paper, a thesis and once it's published, honestly we're lucky to have at least some source code available.

I'm not saying it's impossible, though enforcing rules on data scientist to write `setup.py`s, publishing and maintaining packages, or else reaching out to other data scientist who published that dependency source code few years ago to do all of this themselves... I don't see that likely.

We're not talking about the mainstream DS approaches, those will at some point find its way into numpy or scikit learn... We're talking about the edge cases. 

I would say there's no need to be this strict and look down on vcs dependecies in Pipfiles for prod code of a data science notebook image.

**Comment by vpavlin** [comment]
I am with @fridex here - our role is not to promote something we know is wrong, but help users to get to a better state.

Scientific projects suffer from not using any good practices which result in people implementing a lot of things from scratch over and over. (Data) science these days is more and more about software engineering, so I guess that means scientists will have to become better software engineers?:)

IIUC the origin of this thread is about submodules - and we all agreed that is a no-go for anything we want to "support"

I would not be that strict about git dependencies as long as they point to a specific commit - never install from a branch (master or anything else). But I personally am not angry when you'd pin it to a specific commit.

That said, we do this in ODH too and it bit us before, so we will make sure to release our code properly soon.
